# This is the production variant of
# docker deployment for pre-r app
version: '3'
services:
  # development instance
  tutable-development:
    image: index.docker.io/tutable/backend:development
    container_name: 'tutable-development'
    ports:
      - 3000:3000
    links:
      - database
    depends_on:
      - database
    environment:
      - NODE_ENV=development
      - MONGO_HOST=database
      - MONGO_DB=tutable-development
    env_file:
      - .env

  # production instance
  tutable:
    image: index.docker.io/tutable/backend:master
    container_name: 'tutable'
    ports:
      - 3001:3000
    links:
      - database
    depends_on:
      - database
    environment:
      - NODE_ENV=production
      - MONGO_HOST=database
      - MONGO_DB=tutable
    env_file:
      - .env

  tutable-admin:
    image: index.docker.io/tutable/tutable-webapp:latest
    container_name: 'tutable-admin'
    ports:
      - 8001:8001

  # database configuration for the project
  database:
    image: mongo:3.4.0
    container_name: 'mongodb'
    volumes:
      - ./data/db:/data/db
    restart: always
    ports:
      - "27017:27017"
  # nginx for port forwarding and proxy server
  nginx: 
    image: nginx:latest
    container_name: 'nginx'
    depends_on:
      - tutable
      - tutable-development
    ports:
      - "80:80"
    volumes:
      - ./configurations/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./certs:/etc/nginx/certs
  
  watchtower:
    image: v2tec/watchtower
    container_name: 'watchtower'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.docker/config.json:/config.json
    command: --interval 10 --cleanup