# This is the production variant of
# docker deployment for pre-r app

version: '3.6'
services:

  web:
    build: .
    container_name: web_node
    command: bash -c "npm start"
    volumes:
      - .:/app
      - .:/app/node_modules
    expose:
      - "3000"

